import type { Metadata } from 'next';
import { Roboto, Raleway, DM_Sans, IBM_Plex_Sans, Inter } from 'next/font/google';
import './globals.css';
import { FormProvider } from '@/context/userContext';

const roboto = Roboto({
  variable: '--font-Roboto',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

const raleway = Raleway({
  variable: '--font-Raleway',
  subsets: ['latin'],
});

const DMSans = DM_Sans({
  variable: '--font-DM_Sans',
  subsets: ['latin'],
});

export const iBM_Plex_Sans = IBM_Plex_Sans({
  variable: '--font-IBM_Plex_Sans',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '200', '600'],
});

export const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${raleway.variable} ${DMSans.variable} ${iBM_Plex_Sans.variable} ${inter.variable} antialiased`}
      >
        <FormProvider>{children}</FormProvider>
      </body>
    </html>
  );
}
